workflows:
  android-apk-release:
    name: Android APK Release
    max_build_duration: 60

    environment:
      flutter: 3.22.3
      java: 17
      vars:
        PROJECT_DIR: "BMA"

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper

    scripts:
      - name: Print environment
        script: |
          flutter --version
          dart --version
          java -version
          echo "Working directory:"
          pwd
          echo "Project dir: $PROJECT_DIR"
          ls -la

      - name: Install dependencies
        script: |
          cd $PROJECT_DIR
          flutter pub get

      - name: Run code generation (build_runner)
        script: |
          cd $PROJECT_DIR
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK (Release)
        script: |
          cd $PROJECT_DIR
          flutter build apk --release

    artifacts:
      - BMA/build/app/outputs/flutter-apk/app-release.apk
      - BMA/build/**/outputs/**/mapping.txt

    publishing:
      email:
        recipients:
          - khushalc@fynd-external.com
