buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.1.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22"
    }
}

// IMPORTANT:
// Do NOT add repositories in allprojects{} when repositoriesMode is set to FAIL_ON_PROJECT_REPOS in settings.gradle.
// Repositories must be declared only in settings.gradle.
