workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      java: 11
      
    triggering:
      events:
        - push
        - pull_request
      branch:
        patterns:
          - pattern: main
            include: true
          - pattern: develop
            include: true
            
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          
      - name: Generate database code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
          
      - name: Build APK for Android only
        script: |
          flutter build apk --release --no-tree-shake-icons -v
          
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
    publishing:
      email:
        recipients:
          - kalyanibadgujar@gmail.com
        notify:
          success: true
          failure: true
